name: Daily Querying Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight (adjust as needed)

permissions:
  contents: write
  packages: read


jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log into GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull prebuilt image
        run: docker pull ghcr.io/${{ github.repository_owner }}/rent-aggregator:latest

      - name: Run scraper
        run: |
          mkdir -p data logs
          docker run --rm \
            -v ${{ github.workspace }}/data:/app/data \
            -v ${{ github.workspace }}/logs:/app/logs \
            ghcr.io/${{ github.repository_owner }}/rent-aggregator:latest

      - name: Commit and push changes
        run: |
          git config user.email "mschilling52019@gmail.com"
          git config user.name "MattBot"
          git add data/*.sqlite || echo "No data updates"
          git add logs/app.log
          git commit -m "$(date) Run"
          git push origin main