name: PR Check

on:
  pull_request:
    branches:
      - main  # Only PRs targeting main will trigger this

jobs:
  docker-scraper-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker (optional, pre-installed on ubuntu-latest)
        run: docker --version

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/rent-aggregator:test .

      - name: Run scraper container (test run)
        run: |
          mkdir -p data logs
          docker run --rm \
            -v ${{ github.workspace }}/data:/app/data \
            -v ${{ github.workspace }}/logs:/app/logs \
            ghcr.io/${{ github.repository_owner }}/rent-aggregator:test

      - name: List output files (for debug)
        run: |
          echo "::group::Data"
          ls -l data
          echo "::endgroup::"
          echo "::group::Logs"
          cat logs/app.log || echo "No log found"
          echo "::endgroup::"
