name: PR Check

on:
  pull_request:
    branches:
      - main  # This will run the check on PRs targeting the `main` branch.

jobs:
  test:
    runs-on: ubuntu-latest  # Use a fresh Ubuntu environment for each run.

    steps:
      # Checkout the code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/rent-aggregator:test .


      # Run tests (assuming pytest is used, adjust if you're using a different test framework)
      - name: Run tests
        run: |
          pytest